# Generated by Django 5.0 on 2024-10-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('seat', models.IntegerField()),
            ],
        ),
    ]
